// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  AssignmentDef = 2,
  Parenthesized = 5,
  Lambda = 6,
  LambdaToken = 7,
  VariableDef = 9,
  LambdaDot = 10,
  Pair = 12,
  Variable = 13
