// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "$OQVQPOOOOQO'#C^'#C^O[QPO'#CoOOQO'#Cj'#CjQVQPOOOaQPO,59ZOOQO-E6h-E6hOaQPO'#CaOOQO'#Cc'#CcOlQPO'#CbOqQPO1G.uOOQO'#Ci'#CiOOQO'#Cr'#CrO!PQPO,58{OOQO'#Ce'#CeOOQO'#Ck'#CkO!_QPO,58|OOQO,59S,59SOOQO1G.g1G.gOOQO-E6i-E6iOOQO'#Cf'#CfOaQPO1G.hO!gQPO7+$S",
  stateData: "!x~ObOS~OdPO~OeTO~OSVOWWOdZO~Od^O~OSVOWWO`cidci~ORbOSVOWWOdZO~OZdOd^O~OSVOWWOdZO`UqRUq~O",
  goto: "!zgPPhPPlltP|!QPl!T![!bPPP!hPP!lTQOS][TVY]ef]XTVY]efT_X`Re`Z[TV]efQSORUSQ`XRc`TROSQYTQ]VUaY]fRfe",
  nodeNames: "⚠ Program AssignmentDef ) ( Parenthesized Lambda LambdaToken \\ VariableDef LambdaDot . Pair Variable",
  maxTerm: 22,
  nodeProps: [
    ["openedBy", 3,"(",10,"LambdaToken"],
    ["closedBy", 4,")",7,"LambdaDot"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "#_~R]XYzYZz]^zpqzxy!]yz!b!O!P!g!Q![!l![!]!}!c!}!l#O#P#Y#R#S!l#T#o!l~!PSb~XYzYZz]^zpqz~!bOS~~!gOR~~!lOZ~~!qSd~!Q![!l!c!}!l#R#S!l#T#o!l~#QP!_!`#T~#YOe~~#_OW~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
